@host=http://localhost:5239

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Carlo",
    "lastName": "van der Vliet",
    "email": "carlovandervliet@gmail.com",
    "password": "TheOneAndOnly007!"
}